### ISSUE TITLE
详细请教一下带epusdt的部署方式

### ISSUE THREAD

**Issue by googidaddy** [Apocalypsor/dujiaoka-docker#2]
![xxx](https://raw.githubusercontent.com/googidaddy/img/master/2022/20220729004014.png)

其他均照着教程做，epusdt也部署了，访问epusdt域名能显示正常hello，这个数据库是缺少了么？我直接用的docker-compose里的数据库（与发卡网站同一个数据库）。

**Comment by Apocalypsor** [comment]
有添加钱包地址吗

**Comment by googidaddy** [comment]
> 有添加钱包地址吗

tg机器人没反应。

**Comment by googidaddy** [comment]
明天早上我再试试。
