### ISSUE TITLE
目前的版本还是2.0.5，现在已经有2.0.6了

### ISSUE THREAD

**Issue by fireinrain** [Apocalypsor/dujiaoka-docker#5]
希望大大更新一下镜像

**Comment by Apocalypsor** [comment]
不会吧，我这个是和官方主分支始终保持同步的，是不是你那边没更新？

**Comment by fireinrain** [comment]
> 不会吧，我这个是和官方主分支始终保持同步的，是不是你那边没更新？

我用docker pull 新的镜像 运行起来，管理页面显示的依然是2.0.5

如图：
![image](https://user-images.githubusercontent.com/14249262/234593206-3a07fcac-7e9e-4174-924d-211639c8a677.png)

**Comment by fireinrain** [comment]
compose 文件的镜像：
<img width="607" alt="image" src="https://user-images.githubusercontent.com/14249262/234594192-6d97b76e-05fa-4e5a-81a2-be8531fa948c.png">

**Comment by fireinrain** [comment]
发现问题了 版本是2.0.6 但是代码里面没改

**Comment by Apocalypsor** [comment]
好的，那应该没什么问题了
