### ISSUE TITLE
提示数据库配置错误！

### ISSUE THREAD

**Issue by Yakamozduan** [Apocalypsor/dujiaoka-docker#6]
![image](https://github.com/Apocalypsor/dujiaoka-docker/assets/9112567/e688c089-a409-4c29-ba84-9d00ba7696f7)

**Comment by bmphjhu906** [comment]
一样的问题。。

**Comment by Apocalypsor** [comment]
是更新过Docker镜像出现了这个问题还是第一次设置就有

**Comment by Yakamozduan** [comment]
> 是更新过Docker镜像出现了这个问题还是第一次设置就有

就看了你的博客，直接用的这个镜像ghcr.io/apocalypsor/dujiaoka:latest，第一次用，docker-compose部署

**Comment by Apocalypsor** [comment]
> > 是更新过Docker镜像出现了这个问题还是第一次设置就有
> 
> 就看了你的博客，直接用的这个镜像ghcr.io/apocalypsor/dujiaoka:latest，第一次用，docker-compose部署

修好了，独角卡官方的bug，拉最新镜像就行

**Comment by bmphjhu906** [comment]
![image](https://github.com/Apocalypsor/dujiaoka-docker/assets/120728683/1001fcc0-1740-4079-bf95-d7dc4f9c2656)
是这个原因吧，id重复了
