### ISSUE TITLE
報錯

### ISSUE THREAD

**Issue by ZenithNovaTech** [Apocalypsor/dujiaoka-docker#8]
LogicException  : Unable to prepare route [api/user] for serialization. Uses Closure.

  at /dujiaoka/vendor/laravel/framework/src/Illuminate/Routing/Route.php:917
    913|      */
    914|     public function prepareForSerialization()
    915|     {
    916|         if ($this->action['uses'] instanceof Closure) {
  > 917|             throw new LogicException("Unable to prepare route [{$this->uri}] for serialization. Uses Closure.");
    918|         }
    919| 
    920|         $this->compileRoute();
    921|

  Exception trace:

  1   Illuminate\Routing\Route::prepareForSerialization()
      /dujiaoka/vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteCacheCommand.php:62

  2   Illuminate\Foundation\Console\RouteCacheCommand::handle()
      /dujiaoka/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36

  Please use the argument -v to see more details.
/usr/lib/python3.10/site-packages/supervisor/options.py:474: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  self.warnings.warn(

**Comment by Apocalypsor** [comment]
是第一次安装报错还是使用了一段时间报错？

**Comment by ZenithNovaTech** [comment]
第一次安装的时候

**Comment by Apocalypsor** [comment]
把 storage 下的东西删掉，权限设置为777再重新安装，我这边测试安装没有问题
